name: opencontentbot
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - expat=2.7.3=h885b0b7_4
  - ffmpeg=4.3.1=ha925a31_0
  - idna=3.11=py310haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - pyyaml=6.0.3=py310hb9a58be_0
  - requests=2.32.5=py310haa95532_1
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - pip:
    - python-dotenv==1.2.1
prefix: C:\Users\zgrg2\anaconda3\envs\opencontentbot
